### ISSUE TITLE
C4Music_v4.0.zip is empty

### ISSUE THREAD

**Issue by TGGamesYT** [MopsTMC/C4Music#10]
when I extracted it from the extractme zip, It showed that it is 24543kb-s big, but when I put it into the folder, it just doesn't show, and if I (without unzipping) open it up its telling me that its empty.

**Comment by TGGamesYT** [comment]
I cant even unzip it because it thinks that its empty

**Comment by MopsTMC** [comment]
Please refer to the pinned issue https://github.com/MopsTMC/C4Music/issues/7#issuecomment-2337459175

**Comment by MopsTMC** [comment]
What Java version are you using? If it's 22 or newer then this is a known issue, I'll be uploading a patch sometime in the future
