### ISSUE TITLE
[Bug] "Lena Raine - Ancestry" plays in the Deep Dark Biome

### ISSUE THREAD

**Issue by DraconicNEO** [MopsTMC/C4Music#3]
I noticed a bug that when I would go into Deep Dark Biomes the music changes to "Lena Raine - Ancestry" and stays stuck on that track until I leave the region. I noticed that something was off about the region before but only recently noticed this issue after getting the currently playing mod and seeing that this song just isn't replaced from the stock one.

**Comment by MopsTMC** [comment]
This is Mojang's intended behaviour and the resource pack doesn't modify it so it's expected. Here's the snippet from 1.19.2 `sounds.json`:
```json
"music.overworld.deep_dark": {
    "sounds": [
      {
        "name": "music/game/ancestry",
        "stream": true
      }
    ]
  }
```
I also mention that in the [Bullet 3 of the Notes section](https://github.com/MopsTMC/C4Music/blob/master/C4Music/C4Music.md#notes). To be fair it was also Mojang's intention for the Warped Forest biome to not play music at all but I changed that anyway. In a future update I might add some extra tracks to the deep dark to make it more interesting

**Comment by DraconicNEO** [comment]
Oh I see, that makes sense I guess.
Though it does feel weird having that be the only part in the game where C418 isn't playing. I do think it would be nice if there were a Deep dark addon similar to the nether addon that replaces the music entirely.

**Comment by MopsTMC** [comment]
Fixed for an upcoming release! You can check the change here: [sounds.json](https://github.com/MopsTMC/C4Music/blob/378e107fd4358c825948a91e24990ada8ada4d30/C4Music/pf33plus/assets/minecraft/sounds.json#L310)
