### ISSUE TITLE
Newest modrinth version archive is empty

### ISSUE THREAD

**Issue by Ishikudeska** [MopsTMC/C4Music#7]
When you download V 3.2 on modrinth the archive has NO, and I repeat, NO files inside.

**Comment by MopsTMC** [comment]
It appears as such intentionally. Do you have issues with it in-game?

**Comment by Ishikudeska** [comment]
No. I downloaded the scripts from here and the previous version. That's how I got it to work.

**Comment by MopsTMC** [comment]
I'll assume you mean modrinth, if you can use the v3.2 file in-game then this is a non-issue as I mentioned earlier. The file itself is not meant to be extracted to protect its contents. Most of its files are in this repository if you want to modify them. If you have a specific problem **in-game** with the latest version please open another github issue

**Comment by MopsTMC** [comment]
You are not to extract C4Music_v4.zip itself. The only thing you have to do is place it to your resource packs directory. It's intended that it shows up empty

**Comment by TGGamesYT** [comment]
> You are not to extract C4Music_v4.zip itself. The only thing you have to do is place it to your resource packs directory. It's intended that it shows up empty

It just doesnt seem to work

It just doesnt show up on the resourcepacks screen

**Comment by Zi7ar21** [comment]
Yes, please re-open this issue, it doesn't work for me on Linux, and when I try opening it, my zip program says it's corrupted.

**Comment by MopsTMC** [comment]
As mentioned above, this is intended behavior. The issue would be Minecraft not being able to read the resourcepack which could happen with Java 22+. If you can confirm that the game is running on Java 22 then this is a known issue that I will be fixing in the future: https://github.com/MopsTMC/C4Music/issues/5
I unfortunately cannot help with general statements such as "It just doesn't seem to work" without any game logs, mod lists or system configuration to work with
