### ISSUE TITLE
C4Discs addon music silent.

### ISSUE THREAD

**Issue by l-Noviem-l** [MopsTMC/C4Music#9]
The music in the C4Discs addon doesn't seem to replace the music but instead mute it altogether. This also happens with the C4Nether addon's pigstep disc. It seems to be fine on versions 1.20+, but 1.21 and over isn't.

**Comment by MopsTMC** [comment]
This file should be usable on 1.20.5+
https://cdn.modrinth.com/data/QSKCFxWX/versions/4BZ4R4xR/C4Discs_1.20.5%2B.zip

**Comment by l-Noviem-l** [comment]
This has seemed to fix it! It does still display the original composer's credits but I'm sure that's probably difficult to change and isn't important really. Thank you. :D
